temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
data <- read.table("household_power_consumption.txt",sep=";",dec=".",header=TRUE)
unlink(temp)
data$Date<-as.Date(data$Date,format='%d/%m/%Y')
data<-subset(data,Date>"2007-01-31" & Date<"2007-02-03")
data$Date<-paste(data$Date,data$Time)
data$Date<-strptime(data$Date,format='%Y-%m-%d %H:%M:%S')
data$Global_active_power<-as.numeric(as.character(data$Global_active_power))
data$Global_reactive_power<-as.numeric(as.character(data$Global_reactive_power))
data$Voltage<-as.numeric(as.character(data$Voltage))
data$Global_intensity<-as.numeric(as.character(data$Global_intensity))
data$Sub_metering_1<-as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2<-as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3<-as.numeric(as.character(data$Sub_metering_3))
png(file="plot2.png",width=480,height=480)
with(data,plot(Date,Global_active_power,type="l",xlab="Day",ylab="Global active power minute averages(kW)",main="Global Active Power from 01/02/2007 to 02/02/2007"))
dev.off()
