temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
data <- read.table("household_power_consumption.txt",sep=";",dec=".",header=TRUE)
unlink(temp)
data$Date<-as.Date(data$Date,format='%d/%m/%Y')
data<-subset(data,Date>"2007-01-31" & Date<"2007-02-03")
data$Global_active_power<-as.numeric(as.character(data$Global_active_power))
data$Global_reactive_power<-as.numeric(as.character(data$Global_reactive_power))
data$Voltage<-as.numeric(as.character(data$Voltage))
data$Global_intensity<-as.numeric(as.character(data$Global_intensity))
data$Sub_metering_1<-as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2<-as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3<-as.numeric(as.character(data$Sub_metering_3))
png(file="plot1.png",width=480,height=480)
hist(data$Global_active_power,col="red",ylim=c(0,1400),xlim=c(0,8), main="Global Active Power on 01/02/2007 and 02/02/2007",xlab="Global active power minute averages (kW)")
dev.off()
